global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nodeexporter'
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'dockerexporter'
    static_configs:
      - targets: ['dockerexporter:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']